---
title: "Analysis of point-count data in the presence of variable survey methodologies and detection error"
subtitle: "Workshop proposal, AOS 2019"
author: "Peter Solymos"
date: "September 20, 2018"
output: pdf_document
---

# Name and affiliation of instructor

**Dr. Peter Solymos** \
Boreal Avian Modelling Project and the Alberta Biodiversity Monitoring Institute \
Department of Biological Sciences, CW 405, Biological Sciences Building \
University of Alberta, Edmonton, Alberta, T6G 2E9, Canada \
Phone: (00-1) 780-492-8534 \
Fax: (00-1) 780-492-7635 \
E-mail: solymos@ualberta.ca \
Web: http://peter.solymos.org

# Number of participants

Expecting at least 10--12 and maximum 20--25 participants.

# Additional costs to participants

No additional costs or charges are required for this workshop.

# Time, space and resource requirements

- **Space and resource requirements:** room with chairs, desks, and electrical outlets suitable for working on laptops; projection equipment, and a whiteboard.
- **Time:** the proposed event is a full day workshop (8 hours long with 3 breaks),
therefore before conference days (all day, 24--25 June) would be preferred.
- Participants are expected to bring their own laptops to the workshop.
- The instructor will provide electronic course material online and on USB sticks.

# Summary of course objectives

This course is aimed towards ornithologists analyzing field observations,
who are often faced by data heterogeneities due to
field sampling protocols changing from one project to another,
or through time over the lifespan of projects, or trying to combine
'legacy' data sets with new data collected by recording units.
Such heterogeneities can bias analyses when data sets are integrated
inadequately, or can lead to information loss when filtered and standardized to
common standards. Accounting for these issues is important for better
inference regarding status and trend of bird species and communities.

Analysts of such 'messy' data sets need to feel comfortable
with manipulating the data, need a full understanding the mechanics of the
models being used (i.e. critically interpreting the results and acknowledging
assumptions and limitations), and should be able to make informed choices when
faced with methodological challenges.

The course emphasizes critical thinking and active learning.
Participants will be asked to take part in the analysis:
first hand analytics experience from start to finish.
We will use publicly available data sets to demonstrate the data manipulation
and analysis. We will use freely available and open-source R packages.

The expected outcome of the course is a solid foundation for further
professional development via increased confidence in applying these methods
for field observations.


# Syllabus

1. Introductions
2. Overview of database relations and operations
3. An overview of regression techniques

Short break

4. Estimating nuisance variables (detection error and its components)

Luch break

5. Estimating occupancy, abundance, and density
6. Acconting for methodological biases
7. Statistical inference and prediction

Short break

8. Q/A related to participants' own projects

Dismissal, optional follow up at nearby watering hole

Note: prior exposure to R programming is necessary, knowledge of basic R object types and their manipulation is expected (arrays, data frames, indexing).
