# A Closer Look at Assumptions {#assumptions}

break them assumptions


Compare how does movement based detection influences estimates (when % increases)


36% of records in BAM is 'heard & seen' and I want to understand how likely the following 2 scenarios are:

- 'seen and heard' means that visual and auditory detections are independent processes, i.e. if it often happens that you spot a bird by just visually, that would distort availability.
- or it means that visual and auditory detections are NOT independent processes, i.e after a vocalization the observer also gets a visual.

Both happen, depending to some extent on the species, but more frequently the second scenario.

If you hear an individual vocalizing, it is much easier to also get a visual. But you do sometimes just see an individual moving and not vocalizing (more often females). How likely you are to spot those individuals can depend on the species, e.g., some species forage in ways that make them more visible.

Andy: My experience is that in forests it's almost entirely auditory, and if you see a bird it's almost certainly after it called. The rare exception might be birds foraging on the ground (e.g. thrushes kicking up leaves), or woodpeckers, but again these are usually heard before being seen even though the auditory signal isn't a song or call. In grasslands, however, it's pretty common to see a bird before hearing it.

JT: I agree with you Andy, but I was thinking of species like American Redstarts that have a fairly flashy and obvious form of feeding as they chase and flycatch insects - it isn't uncommon to see these individuals before hearing them. Ultimately, to go back to Peter's concern, I do not think that the auditory and visual processes can be considered independent.

```{r}
load("_data/josm/josm.rda") # JOSM data

100*table(josm$counts$DetectType1)/sum(table(josm$counts$DetectType1))

aa <- table(josm$counts$SpeciesID, josm$counts$DetectType1)
bb <- aa[,"V"]/rowSums(aa)
hist(bb)
sort(bb[bb > 0.2])
```
